export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const USER = 'USER'
export const HISTORY = 'HISTORY'
export const TIMEIN = 'TIMEIN'
export const TIMEOUT = 'TIMEOUT'
export const REGISTER = 'REGISTER'
